version: '3.9'
services:
  mysql1:
    image: mysql:5.7
    container_name: db1
    volumes:
      - ./dbfiles:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
  node1:
    container_name: api
    ports:
      - '81:8000'
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - .\api:/usr/src/app
    depends_on:
      mysql1:
        condition: service_started
    stdin_open: true
    tty: true
  reactapp:
    container_name: app
    ports:
      - '80:5000'
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - .\app:/usr/src/app
    depends_on:
      node1:
        condition: service_started
    stdin_open: true
    tty: true
